name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer
        uses: php-actions/composer@v5

      - name: Install packages
        uses: "ramsey/composer-install@v1"

      - name: Run tests
        run: composer test
