name: Tests
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: dependencies-composer-${{ runner.os }}-${{ hashFiles('composer.json') }}

      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: 2

      - name: Run tests
        run: composer test
